---
- name: Create folder for file includes.
  file:
    path: "{{ nginx_path }}/includes"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Adding redirection file.
  template:
    src: redirection.conf.j2
    dest: "{{ nginx_includes_path }}/redirection.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Adding fastcgi configuration file.
  template:
    src: fastcgi.conf.j2
    dest: "{{ nginx_path }}/fastcgi.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644   
  notify:
    - reload nginx 

- name: Check if got any SSL certs installed (needed for start nginx)
  stat:
    path: /etc/nginx/certificates/*.*    
  tags: ssl
  register: certificates_check  

- name: Create /etc/nginx/certificates/ (if not exists)
  file:
    path: /etc/nginx/certificates/
    state: directory
    owner: root
    group: root
    mode: 0775
  when: certificates_check.stat.exists == False
  tags: ssl

- name: Generate self signed SSL certificates
  command: >
    openssl req
      -x509    
      -nodes    
      -days 365        
      -newkey rsa:2048
      -subj "/C=US/ST=NY/L=NY/O=NA/CN=${ansible_fqdn}"
      -keyout /etc/nginx/certificates/{{ nginx_vhost_domain }}.key
      -out /etc/nginx/certificates/{{ nginx_vhost_domain }}.pem
  args:
    creates: '/etc/nginx/certificates/{{ nginx_vhost_domain }}.pem'
  when: certificates_check.stat.exists == False
  tags: ssl

- name: Adding WP-Rocket configuration file.
  template:
    src: rocket-wp.conf.j2
    dest: "{{ nginx_includes_path }}/rocket-wp.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Adding drop configuration file.
  template:
    src: drop.conf.j2
    dest: "{{ nginx_includes_path }}/drop.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Adding static configuration file.
  template:
    src: static.conf.j2
    dest: "{{ nginx_includes_path }}/static.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx       

- name: Adding block attacks configuration file.
  template:
    src: block.conf.j2
    dest: "{{ nginx_includes_path }}/block.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx         

- name: Remove default nginx vhost config file (if configured).
  file:
    path: "{{ nginx_default_vhost_path }}"
    state: absent
  when: nginx_remove_default_vhost
  notify: restart nginx

- name: Ensure nginx_vhost_path exists.
  file:
    path: "{{ nginx_vhost_path }}"
    state: directory
  notify: reload nginx

- name: Add managed vhost config file (if any vhosts are configured).
  template:
    src: vhosts.j2
    dest: "{{ nginx_vhost_path }}/{{ nginx_vhosts_filename }}"
    mode: 0644
  when: nginx_vhosts|length > 0
  notify: reload nginx
  tags: vhost

- name: Remove managed vhost config file (if no vhosts are configured).
  file:
    path: "{{ nginx_vhost_path }}/{{ nginx_vhosts_filename }}"
    state: absent
  when: nginx_vhosts|length == 0
  notify: reload nginx
  tags: vhost

- name: Create defined vhost root folder (if not exists).
  file:
    path: "/var/www/{{ nginx_vhost_domain }}"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data